### ISSUE TITLE
Test Survey

### ISSUE THREAD

**Issue by mattm401** [mattm401/collabortweet#15]
Once Sapna has completed the online version of the survey, you should test it and be sure to compare it to the final paper version (i.e., the one that got updated after the group meeting).

**Comment by mattm401** [comment]
Hi @skushnir123 

It would be great if you guys could pilot the following survey:
https://www.surveymonkey.com/r/TR53T8G

What I am most interested in is (i) is the survey clear and (ii) do you feel like the cognitive load or fatigue is high when taking the survey? (i.e. do you feel mentally tired after taking the survey)

When taking the survey, imagine that you have used a thermal camera to capture images or video and you have used this in a video that you uploaded to YouTube. Here are a few good examples to help you get into character:

https://www.youtube.com/watch?v=1DiqL8iFD8g
https://www.youtube.com/watch?v=sRpH-v_uLJw
https://www.youtube.com/watch?v=iRmgnWzi0DE
https://www.youtube.com/watch?v=1PpyvW_w6K8&t=557s

While there is no explicit rush, having feedback by sometime tomorrow would be most helpful.

**Comment by skushnir123** [comment]
everything looked good.
