### ISSUE TITLE
Sticky Button Issue

### ISSUE THREAD

**Issue by mattm401** [mattm401/collabortweet#17]
That buttons occasionally don't work in the interface should be looked into. What causes this? When you guys "hack" the system by stopping/refreshing the page load you cause multiple entries to appear in the database which means we need to clean up the database before we can do IRR and you both don't get to accurately check how many more videos there are to label.

**Comment by skushnir123** [comment]
error in terminal:Unhandled rejection TypeError: Cannot read property 'taskName' of undefined
    at /Users/samuelkushnir/Documents/GitHub/collabortweet/server.js:334:23

**Comment by mattm401** [comment]
Can you copy in the whole string of errors? Maybe just enclosing this space with a try/catch will allow us to bypass the error?
